app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', function () {
    return view('pages/landing_page');
});


Route::get('courses','CoursesController@index');
Route::get('courses/create','CoursesController@create');
Route::post('courses','CoursesController@store');
Route::get('courses/delete/{id}','CoursesController@delete');
Route::post('courses/{id}/store-user','CoursesController@store_user');
Route::get('courses/update/{id}','CoursesController@update_course');

Route::get('courses/{id}/add-lesson', 'LessonsController@create');
Route::post('courses/{id}/add-lesson','LessonsController@store_lesson');
Route::get('courses/{id}/delete/{lessNo}','LessonsController@delete');
Route::get('courses/{id}/update/{lessNo}','LessonsController@update_lesson');

Route::post('courses/{id}/quizzes/create','QuizzesController@store');
Route::post('courses/{id}/quizzes/delete/{quizId}','QuizzesController@delete');
Route::get('courses/{id}/quizzes/update/{quizId}','QuizzesController@edit');
Route::post('courses/{id}/quizzes/{quizId}','QuizzesController@update');
Route::get('quiz/{courseId}', 'QuizzesController@takeTest');
Route::post('quiz/{courseId}', 'QuizzesController@grade');
Route::get('studentGrades', 'QuizzesController@getStudentGrades');
Route::get('teacherGrades', 'QuizzesController@getTeacherGrades');

Route::get('courses/{id}/{lessNo}','LessonsController@show_lesson');
Route::post('courses/{id}/{lessNo}','LessonsController@save');
Route::get('courses/{id}','CoursesController@show_course');
Route::post('courses/{id}','CoursesController@save');

Route::get('dashboard','PagesController@dashboard');
Route::get('about','PagesController@about');


Route::resource('user', 'UsersController',
                ['only' => ['edit', 'update']]);


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController'
]);

Route::get('forum','TopicController@index');
Route::post('forum/delete', 'TopicController@delete');
Route::get('forum/newTopic', 'TopicController@newTopic');
Route::post('forum/newTopic', 'TopicController@createTopic');
Route::get('forum/show/{id}/{pageNo}', 'CommentsController@pages');
Route::get('forum/show/{id}', 'CommentsController@showComments');
Route::post('forum/show/{id}','CommentsController@addComment');
Route::post('comments/delete', 'CommentsController@delete');
Route::get('forum/{pageNo}','TopicController@page');

Route::get('/sudo', 'SudoController@index');
Route::get('sudo/users', 'SudoController@showUsers');
Route::post('sudo/users/delete', 'SudoController@deleteUser');
Route::post('sudo/users/elevate', 'SudoController@elevateUser');
Route::post('sudo/users/downgrade', 'SudoController@downgradeUser');
Route::get('sudo/courses', 'SudoController@showCourses');
Route::post('sudo/courses/delete', 'SudoController@deleteCourse');
Route::get('sudo/topics', 'SudoController@showTopics');
Route::post('sudo/topics/delete', 'SudoController@deleteTopic');

resources/views/layouts/application.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>TTTTeam</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="{{url('css/application.css')}}" rel="stylesheet">
    @yield('styles')

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.js"></script>
    @yield('scripts')

    <?php
      use App\Models\Course;
      use App\Models\Topic;
      use App\Models\User;
    ?>
  </head>
  <body>
    <div class="wrapper">
      <div class="left-navbar">
        <div class="user-and-avatar">
          <img src="{{Auth::user()->get_jpg_photo_path()}}" width="50px">
          <p class="name">{!! Auth::user()->firstName !!} {!! Auth::user()->lastName !!}</p>
        </div>

        <div id="main-menu">
          <div class="list-group panel">
            <div class="dashboard menu-item">
              @if (Auth::user()->isAdmin())
                <a href="/sudo" class="list-group-item">
                  <i class="fa fa-windows"></i>
                  Admin Dashboard
                </a>
              @else
                <a href="/dashboard" class="list-group-item">
                  <i class="fa fa-windows"></i>
                  Dashboard
                </a>
              @endif
            </div>
            <div class="menu-item">
              <a href="#list1" class="list-group-item" data-toggle="collapse" data-parent="#main-menu">
                <i class="fa fa-book"></i>
                Courses
              </a>
            </div>
            <div class="collapse" id="list1">
              <div class="subitem-title">
                @if (count(Course::all()) > 0)
                  <p>All Courses</p>
                @endif
              </div>
              @foreach (Course::all() as $course)
                <div class="subitem">
                  <a href="{{url('/courses',$course->id)}}" class="list-group-item">
                    <i class="fa fa-file-text-o"></i>
                    {!!$course->title!!}
                  </a>
                </div>
              @endforeach
              <div class="subitem-title">
                <p>Actions</p>
              </div>
              <div class="subitem">
                @if (Auth::user()->isStudent())
                  <a href="{{url('/dashboard')}}" class="list-group-item">
                    <i class="fa fa-book"></i>
                    View Courses
                  </a>
                @else
                  <a href="{{url('/courses/create')}}" class="list-group-item">
                    <i class="fa fa-plus"></i>
                    New Course
                  </a>
                @endif
              </div>
            </div>

            <div class="menu-item {{ Request::is('forum') ? 'active' : '' }}">
              <a href="/forum" class="list-group-item">
                <i class="fa fa-comments-o"></i>
                Forum
              </a>
            </div>

            <div class="menu-item {{ Request::is('quiz') ? 'active' : '' }}">
              @if (Auth::user()->isStudent())
                <a href="/studentGrades" class="list-group-item">
                  <i class="fa fa-flash"></i>
                  Quizzes
                </a>
              @else
                <a href="/teacherGrades" class="list-group-item">
                  <i class="fa fa-flash"></i>
                  Quizzes
                </a>
              @endif
            </div>
          </div>
        </div>
      </div>
      <div class="header">
        <div class="header-options">
          <a href="/dashboard">
            <i class="fa fa-home fa-lg"></i>
          </a>
          <a href="{{route('user.edit', Auth::user()->id)}}">
            <i class="fa fa-user fa-lg"></i>
          </a>
          <a href="/auth/logout">
            <i class="fa fa-sign-out fa-lg"></i>
            Log out
          </a>
        </div>
      </div>
      <div class="content">
        @yield('content')
    </div>
      </div>
  </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>TTTTeam</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="{{url('css/guest.css')}}" rel="stylesheet">
    @yield('styles')

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.js"></script>
  </head>
  <body>
    <div class="wrapper">
      <nav class="navbar navbar-default header">
        <div class="col-lg-2 col-md-2 col-sm-2"></div>
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href = "/" class="logo">
              <img src="/images/logo_with_text.png">
            </a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-1 move-right"></div>
          <div class="collapse navbar-collapse" id="collapse-menu">
            <ul class="nav navbar-nav navbar-right">
                <li class = "menu-item menu-item-active"><a href="/">HOME</a></li>
                <li class = "menu-item"><a href="/about">ABOUT</a></li>
                  <li class = "menu-item"><a href="/auth/login">LOGIN</a></li>
                  <li class = "menu-item"><a href="/auth/register">SIGN UP</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
          @yield('content')
      </div>
      <div class="footer">
        <img src="/images/logo.png" width="40px">
      </div>
    </div>
  </body>
</html>